// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230912122411_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiteratureID")
                        .HasColumnType("int");

                    b.Property<int>("MathsID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("LiteratureID");

                    b.HasIndex("MathsID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Literature", b =>
                {
                    b.Property<int>("LiteratureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiteratureID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<double>("Exam1")
                        .HasColumnType("float");

                    b.Property<double>("Exam2")
                        .HasColumnType("float");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdID")
                        .HasColumnType("int");

                    b.HasKey("LiteratureID");

                    b.ToTable("Literatures");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Maths", b =>
                {
                    b.Property<int>("MathsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MathsID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<double>("Exam1")
                        .HasColumnType("float");

                    b.Property<double>("Exam2")
                        .HasColumnType("float");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdID")
                        .HasColumnType("int");

                    b.HasKey("MathsID");

                    b.ToTable("Mathses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.StudentInfo", b =>
                {
                    b.Property<int>("StdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StdID"));

                    b.Property<int>("AbsentDay")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiteratureID")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MathsID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdBirthDay")
                        .HasColumnType("int");

                    b.Property<string>("StdClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdNum")
                        .HasColumnType("int");

                    b.Property<string>("StdSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TC")
                        .HasColumnType("int");

                    b.HasKey("StdID");

                    b.HasIndex("LiteratureID");

                    b.HasIndex("MathsID");

                    b.ToTable("StudentInfos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Department", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Literature", "Literature")
                        .WithMany("Departments")
                        .HasForeignKey("LiteratureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Maths", "Maths")
                        .WithMany("Departments")
                        .HasForeignKey("MathsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Literature");

                    b.Navigation("Maths");
                });

            modelBuilder.Entity("EntityLayer.Concrete.StudentInfo", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Literature", "Literature")
                        .WithMany("StudentInfos")
                        .HasForeignKey("LiteratureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Maths", "Maths")
                        .WithMany("StudentInfos")
                        .HasForeignKey("MathsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Literature");

                    b.Navigation("Maths");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Literature", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("StudentInfos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Maths", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("StudentInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
